// <auto-generated />
using DpsWebManagement.Providers;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DpsWebManagement.Migrations
{
    [DbContext(typeof(DpsDbContext))]
    partial class DpsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DpsWebManagement.Providers.Model.DpsCertificate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PemPrivateKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PemPublicKey")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DpsCertificates");
                });

            modelBuilder.Entity("DpsWebManagement.Providers.Model.DpsEnrollmentDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DpsEnrollmentGroupId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PathToPfx")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PemPrivateKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PemPublicKey")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DpsEnrollmentGroupId");

                    b.ToTable("DpsEnrollmentDevices");
                });

            modelBuilder.Entity("DpsWebManagement.Providers.Model.DpsEnrollmentGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DpsCertificateId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PemPrivateKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PemPublicKey")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DpsCertificateId");

                    b.ToTable("DpsEnrollmentGroups");
                });

            modelBuilder.Entity("DpsWebManagement.Providers.Model.DpsEnrollmentDevice", b =>
                {
                    b.HasOne("DpsWebManagement.Providers.Model.DpsEnrollmentGroup", "DpsEnrollmentGroup")
                        .WithMany("DpsEnrollmentDevices")
                        .HasForeignKey("DpsEnrollmentGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DpsEnrollmentGroup");
                });

            modelBuilder.Entity("DpsWebManagement.Providers.Model.DpsEnrollmentGroup", b =>
                {
                    b.HasOne("DpsWebManagement.Providers.Model.DpsCertificate", "DpsCertificate")
                        .WithMany("DpsEnrollmentGroups")
                        .HasForeignKey("DpsCertificateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DpsCertificate");
                });

            modelBuilder.Entity("DpsWebManagement.Providers.Model.DpsCertificate", b =>
                {
                    b.Navigation("DpsEnrollmentGroups");
                });

            modelBuilder.Entity("DpsWebManagement.Providers.Model.DpsEnrollmentGroup", b =>
                {
                    b.Navigation("DpsEnrollmentDevices");
                });
#pragma warning restore 612, 618
        }
    }
}
